name: CI/CD

on:
    pull_request:
        branches:
            - "**"
    push:
        branches:
            - "**"
jobs:
# Stage1   linting .... static status check 
    test:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout code and setup python and dependencies 
           uses: actions/checkout@v4
         - uses: actions/setup-python@v5
           with:
            python-version: '3.10'
            cache: 'pip' # caching pip dependencies
         - run: pip install -r requirements.txt
         - name: linting code
           run: pip install flake8 && pip install pylint 
        #  - run: flake8 . --count --select=E9,F63,F7,F82 --
         - run: pylint


    release:
        needs: test
        runs-on: ubuntu-latest
        steps:
         - name: Checkout code
           uses: actions/checkout@v3
           with:
            fetch-depth: 0

         - name: Python Semantic Release
           uses: python-semantic-release/python-semantic-release@master
           with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
